### ISSUE TITLE
Putting metric without dimension.

### ISSUE THREAD

**Issue by antoxas1986** [mixmaxhq/cloudwatch-metrics#36]
When putting metric without dimension your code false to report metric to Cloudwatch.

```
let metrics = new cloudwatchMetrics.Metric('MyNamespace', 'Count', [], {
    enabled,
    sendInterval: 60 * 1000, // 1 minute.
    sendCallback: (err) => {
      if (err) {
        console.error('cloudwatchMetrics error', err);
      }
    }
  });

metrics.put('1', 'b');
```
This will error out: 

```
TypeError: Cannot read property 'Name' of undefined
at ParamValidator.validateStructure (/node_modules/aws-sdk/lib/param_validator.js:59:25)
at ParamValidator.validateMember (/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validateList (/node_modules/aws-sdk/lib/param_validator.js:103:14)
at ParamValidator.validateMember (/node_modules/aws-sdk/lib/param_validator.js:90:21)
at ParamValidator.validateStructure (/node_modules/aws-sdk/lib/param_validator.js:75:14)
at ParamValidator.validateMember (/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validateList (/node_modules/aws-sdk/lib/param_validator.js:103:14)
at ParamValidator.validateMember (/node_modules/aws-sdk/lib/param_validator.js:90:21)
at ParamValidator.validateStructure (/node_modules/aws-sdk/lib/param_validator.js:75:14)
at ParamValidator.validateMember (/node_modules/aws-sdk/lib/param_validator.js:88:21)
```

However, If include an empty array, the metric will be reported to Cloudwatch.
```
metrics.put('1', 'b', []);
```

Please, update the code to be able to put metric without dimensions, or update documentation and mention the required empty array when putting metric. Thanks.

**Comment by ttacon** [comment]
Hi @antoxas1986 , [the docs do show this here](https://github.com/mixmaxhq/cloudwatch-metrics#publishing-metric-data). Happy to add a new example if you can provide a more fleshed out example of what you're trying to accomplish!

**Comment by antoxas1986** [comment]
We use it without dimensions and without an empty array. After few updates for aws-sdk and for your library, our metrics stop reporting to cloudwatch. And now we debug to find out that if we put an empty array it starts reporting. I understand it is the edge case, so maybe add more documentation around this topic.

**Comment by Nick-Rivera-Meredith** [comment]
This is also happening to us. When we call `put` with two arguments (i.e. `metric.put(value, metric)`), we get the error _Cannot read property 'Name' of undefined_.

When stepping into the code for cloudwatch-metrics, it looks like calling `put` with two arguments takes the code down this path.

```js
Metric.prototype.put = function(...args) {
  if (args.length === 3) {
    const [value, metricName] = args;
    const shouldInheritUnits = Array.isArray(args[2]);
    const units = shouldInheritUnits ? this.units : args[2];
    const additionalDimensions = shouldInheritUnits ? args[2] : [];
    return this._put(value, metricName, units, additionalDimensions);
  } else if (args.length === 2) {
    // 👇 This path here.
    return this._put(...args, this.units);
  }
  return this._put(...args);
};
```

`_put` has four arguments. When `this._put(...args, this.units)` is executed, the last argument, `additionalDimensions`, is `undefined`. When `additionalDimensions` is `undefined`, the line `self.defaultDimensions.concat(additionalDimensions)`
concatenates the value `undefined` to the `Dimensions` array. This causes an error when the metrics are sent to CloudWatch.

```js
Metric.prototype._put = function(value, metricName, units, additionalDimensions) {
  var self = this;
  // Only publish if we are enabled
  if (self.options.enabled) {
    var payload = {
      MetricName: metricName,
      // 👇 additionalDimensions is undefined on this line.
      Dimensions: self.defaultDimensions.concat(additionalDimensions),
      Unit: units,
      Value: value
    };
    if (this.options.withTimestamp) {
      payload.Timestamp = new Date().toISOString();
    }
    if (this.options.storageResolution) {
      payload.StorageResolution = this.options.storageResolution;
    }

    self._storedMetrics.push(payload);

    // We need to see if we're at our maxCapacity, if we are - then send the
    // metrics now.
    if (self._storedMetrics.length === self.options.maxCapacity) {
      clearInterval(self._interval);
      self._sendMetrics();
      self._interval = setInterval(() => {
        self._sendMetrics();
      }, self.options.sendInterval);
    }
  }
};
```
